LEGS=[
 dict(no=1,frm="Courmayeur",to="Valgrisenche",k0=0,k1=48.5,
  head="Warm, dry, sunny. A sun-and-water leg, not a cold one.",
  crux="Col Passo Alto (2856 m) and Col de la Crosatie (2823 m), 17:30–19:45. 8–10 °C, wind light. Sunset 19:48 — you light up on the Crosatie descent.",
  take=["Sun kit: cap, dark glasses, sunscreen — 21 °C at La Thuile and full UV at 2800 m",
        "Full water capacity out of Courmayeur and again at Deffeyes",
        "Headtorch accessible from Deffeyes onward, not buried",
        "A light windshell for the two cols"],
  leave=["Insulated jacket","Warm gloves","Anything for rain beyond the mandatory shell"]),
 dict(no=2,frm="Valgrisenche",to="Cogne",k0=48.5,k1=104.0,
  head="Night one, and the highest ground of the race. First leg where cold is real.",
  crux="Col Fenêtre (2844 m) 02:37 at 3.9 °C, Col Entrelor (3004 m) 06:32 at 3.2 °C / feels 0.5 °C. Clear and near-calm, so it radiates — standing still costs you fast. Col Loson (3295 m, route high point) late morning, 8 °C, gusts to 34 km/h.",
  take=["Warm hat and real gloves — worn, not carried, from Chalet de l'Epée",
        "Insulated layer for the two night cols",
        "Both headtorches charged; this is a 9-hour night",
        "Sun kit again for Loson and the drop into Cogne — 22 °C at the life base"],
  leave=["Waterproof trousers stay mandatory-kit-only","Nothing else — this leg earns its weight"]),
 dict(no=3,frm="Cogne",to="Donnas",k0=104.0,k1=149.8,
  head="The hot one. 22 °C at Cogne, and a 1000 m climb in the afternoon sun.",
  crux="Lillaz → Finestra di Champorcher (2827 m) in the heat of Monday afternoon, topping out 21:07 at 8.9 °C. Then 2450 m of descent into Donnas, where it is still 20 °C at 04:00.",
  take=["Maximum water carry and salt — this is the dehydration leg, not the cold one",
        "Sun protection for the whole Lillaz climb",
        "One light layer for the Finestra–Miserin–Dondena plateau after dark"],
  leave=["Insulated jacket","Warm gloves","Long tights"]),
 dict(no=4,frm="Donnas",to="Gressoney",k0=149.8,k1=203.8,
  head="Longest, lowest, hottest. 21 hours and almost no cold in it.",
  crux="Nothing thermal. The Coda–Barma–Colle della Vecchia traverse runs 10–15 °C all Tuesday night with gusts under 35 km/h. The climb out of Donnas in full Tuesday sun is the real problem.",
  take=["Heat kit: water, salt, sun sleeves or a soaked buff",
        "A windshell is enough for the whole night section",
        "Fresh headtorch batteries at Gressoney is a better use of the stop than layers"],
  leave=["Insulated jacket","Warm gloves","Long tights"]),
 dict(no=5,frm="Gressoney",to="Valtournenche",k0=203.8,k1=237.5,
  head="Short, and the wind arrives. Bring the windproof, not the raincoat.",
  crux="Col Pinter (2782 m) at first light, 4.7 °C but gusts to 70 km/h — that is 0 °C on your skin. Same again on the Grand Tournalin / Col de Nannaz ridge at midday, gusts near 65 km/h. Freezing level drops to 3430 m.",
  take=["Windproof jacket — the single most useful item on this leg",
        "Gloves, hat, buff, worn over Pinter before dawn",
        "Glasses for wind-blown grit on the Nannaz ridge"],
  leave=["Nothing extra — but this is where you stop leaving the warm kit behind"]),
 dict(no=6,frm="Valtournenche",to="Ollomont",k0=237.5,k1=286.5,
  head="THE COLD LEG. The airmass changes Wednesday night. Take everything.",
  crux="Two hours above 2650 m in the coldest part of the night: Rif. Cuney (2655 m) 02:17 at 0.3 °C, Col de Chaleby 02:49, Biv. Clermont 03:24, Col de Vessonaz (2788 m) 03:36 at 0.2 °C / feels −4 °C. Clear and nearly windless, which is exactly what makes it bite — expect frost on grass and rock and greasy slabs on the descent to Oyace.",
  take=["Insulated jacket — worn, from Fenêtre du Tsan onward",
        "Warm hat, warm gloves, AND a dry spare pair",
        "Long tights or leg covers","Windshell over the top for Vessonaz",
        "Buff over the face for the Cuney plateau",
        "Something hot at Valtournenche before you leave"],
  leave=["Nothing. This is the leg you load up for."]),
 dict(no=7,frm="Ollomont",to="Courmayeur",k0=286.5,k1=336.5,
  head="Warm afternoon, then the second cold night — and Malatrà at midnight.",
  crux="Col Malatrà (2921 m) around 00:43 at 0.0 °C / feels −3 °C, near-calm. Freezing level 3220 m, the lowest all week. Cold hands on the chains, frost on the rock in the notch. Then a long cold descent: Bonatti 5.6 °C, Mont de la Saxe 4.2 °C at 04:00.",
  take=["The same full warm kit as leg 6 — do not send it home at Ollomont",
        "Warm gloves for the Malatrà chains, plus the dry spare",
        "Insulated jacket and hat from Bosses onward",
        "Fresh headtorch batteries at Ollomont — 9 more hours of dark"],
  leave=["Nothing until you are down off Malatrà"]),
]
